SWEP.Base = "weapon_308_robloxsword"
SWEP.PrintName = "Linked Sword"
SWEP.AdminOnly=true
SWEP.Category = "x308 Base | Melee"
SWEP.WorldModel = "models/weapons/w_crowbar.mdl"
SWEP.Slot = 0
SWEP.Spawnable = true
SWEP.ShowWorldModel=false
SWEP.Primary.Automatic=true
