att.PrintName="[308]Fastest Reloading"
att.Icon=Material("icon16/clock.png")
att.Description="Never care about your gun's remain ammo now."
att.Desc_Pros={}
att.Desc_Cons={"- But side effect still valid right?"}
att.AutoStats=true
att.Slot="perk"
att.Mult_SightTime=2
att.Mult_ReloadTime=.5
att.Mult_Recoil=1.6
att.Mult_RPM=.8
att.MagReducer=true
att.Mult_DrawTime=1.15
att.Mult_HolsterTime=1.15